// ═══════════════════════════════════════════════════
// OCULOPS — Reports Module
// 100-Year UX: strictly OLED Black, Gold, 1px Primitives
// ═══════════════════════════════════════════════════

import { useState } from 'react'
import { useDeals } from '../../hooks/useDeals'
import { useLeads } from '../../hooks/useLeads'
import { useTasks } from '../../hooks/useTasks'
import { useFinance } from '../../hooks/useFinance'

function Reports() {
  const { deals, totalValue, weightedValue, loading: dealsLoading } = useDeals()
  const { leads, loading: leadsLoading } = useLeads()
  const { tasks, completionRate, loading: tasksLoading } = useTasks()
  const { mrr, totalRevenue, totalExpenses, netIncome, loading: financeLoading } = useFinance()
  const [copied, setCopied] = useState(false)
  const [period, setPeriod] = useState('week')

  const loading = dealsLoading || leadsLoading || tasksLoading || financeLoading

  const closedDeals = deals.filter(d => d.stage === 'closed_won')
  const activeDeals = deals.filter(d => !['closed_won', 'closed_lost'].includes(d.stage))
  const doneTasks = tasks.filter(t => t.status === 'done')
  const newLeads = leads.length

  const periodLabel = period === 'week' ? 'CURRENT WEEK' : 'CURRENT MONTH'

  const reportText = `
OCULOPS — BUSINESS TELEMETRY REPORT
${periodLabel} — ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }).toUpperCase()}
${'='.repeat(60)}

[ COMMERCIAL INTEL ]
> ACTIVE LEADS:        ${newLeads}
> PIPELINE DEALS:      ${activeDeals.length}
> CLOSED DEALS (WON):  ${closedDeals.length}
> PIPELINE GROSS VAL:  $${totalValue.toLocaleString()}
> WEIGHTED PROJECTION: $${Math.round(weightedValue).toLocaleString()}

[ OPERATIONAL METRICS ]
> TOTAL TASKS:         ${tasks.length}
> TASKS COMPLETED:     ${doneTasks.length}
> COMPLETION RATE:     ${completionRate}%

[ FINANCIAL DATA ]
> RUN RATE (MRR):      $${mrr.toLocaleString()}
> GROSS REVENUE:       $${totalRevenue.toLocaleString()}
> TOTAL EXPENSES:      $${totalExpenses.toLocaleString()}
> NET INCOME (PROFIT): $${netIncome.toLocaleString()}

GENERATED BY OCULOPS V10.3 / SYSTEM OVERRIDE
`.trim()

  const copyReport = () => {
    navigator.clipboard.writeText(reportText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (loading) return (
    <div className="fade-in mono text-xs" style={{ padding: '2rem', textAlign: 'center', color: 'var(--color-primary)' }}>
      /// COMPILING METRICS...
    </div>
  )

  return (
    <div className="fade-in" style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* ── HEADER ── */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: '16px', borderBottom: '1px solid var(--color-border)', marginBottom: '24px' }}>
        <div>
          <h1 style={{ fontFamily: 'var(--font-editorial)', color: 'var(--color-primary)', letterSpacing: '0.05em', margin: 0 }}>TELEMETRY REPORTS</h1>
          <span className="mono text-xs text-tertiary">BUSINESS METRICS SNAPSHOT // EXPORTABLE DOSSIER</span>
        </div>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button className="btn btn-ghost mono" style={{ fontSize: '9px', padding: '6px 16px', border: period === 'week' ? '1px solid var(--color-primary)' : '1px solid var(--border-subtle)', background: period === 'week' ? 'var(--color-primary)' : 'transparent', color: period === 'week' ? '#000' : 'var(--text-tertiary)' }} onClick={() => setPeriod('week')}>WEEKLY</button>
          <button className="btn btn-ghost mono" style={{ fontSize: '9px', padding: '6px 16px', border: period === 'month' ? '1px solid var(--color-primary)' : '1px solid var(--border-subtle)', background: period === 'month' ? 'var(--color-primary)' : 'transparent', color: period === 'month' ? '#000' : 'var(--text-tertiary)' }} onClick={() => setPeriod('month')}>MONTHLY</button>
        </div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '24px', paddingBottom: '32px' }}>

        {/* ── KPI STRIP ── */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1px', background: 'var(--border-subtle)', border: '1px solid var(--color-border)' }}>
          <div style={{ background: '#000', padding: '16px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <div className="mono text-2xs" style={{ color: 'var(--text-tertiary)' }}>ACTIVE LEADS</div>
            <div className="mono" style={{ fontSize: '20px', fontWeight: 'bold', color: 'var(--color-info)' }}>{newLeads}</div>
          </div>
          <div style={{ background: '#000', padding: '16px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <div className="mono text-2xs" style={{ color: 'var(--text-tertiary)' }}>PIPELINE DEALS</div>
            <div className="mono" style={{ fontSize: '20px', fontWeight: 'bold', color: 'var(--color-primary)' }}>{activeDeals.length}</div>
          </div>
          <div style={{ background: '#000', padding: '16px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <div className="mono text-2xs" style={{ color: 'var(--text-tertiary)' }}>TASK COMPLETION</div>
            <div className="mono" style={{ fontSize: '20px', fontWeight: 'bold', color: 'var(--color-success)' }}>{completionRate}%</div>
          </div>
          <div style={{ background: '#000', padding: '16px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <div className="mono text-2xs" style={{ color: 'var(--text-tertiary)' }}>SYSTEM MRR</div>
            <div className="mono" style={{ fontSize: '20px', fontWeight: 'bold', color: 'var(--color-success)' }}>${mrr.toLocaleString()}</div>
          </div>
        </div>

        {/* ── DATA MATRICES ── */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '24px' }}>

          <div style={{ border: '1px solid var(--color-border)', background: 'var(--color-bg-2)', display: 'flex', flexDirection: 'column' }}>
            <div className="mono text-xs font-bold" style={{ padding: '12px 16px', background: 'var(--border-subtle)', borderBottom: '1px solid var(--color-border)', color: 'var(--color-primary)' }}>
              /// COMMERCIAL PIPELINE
            </div>
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              {[
                { label: 'PIPELINE LEADS', value: newLeads },
                { label: 'ACTIVE DEALS', value: activeDeals.length },
                { label: 'CLOSED DEALS (WON)', value: closedDeals.length },
                { label: 'GROSS PIPELINE VAL', value: `$${totalValue.toLocaleString()}` },
                { label: 'WEIGHTED AVERAGE', value: `$${Math.round(weightedValue).toLocaleString()}` },
              ].map(({ label, value }, idx) => (
                <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 16px', borderBottom: idx < 4 ? '1px solid var(--border-subtle)' : 'none', background: idx % 2 === 0 ? 'transparent' : '#000' }}>
                  <span className="mono text-xs" style={{ color: 'var(--color-text-2)' }}>{label}</span>
                  <span className="mono text-xs font-bold" style={{ color: 'var(--color-text)' }}>{value}</span>
                </div>
              ))}
            </div>
          </div>

          <div style={{ border: '1px solid var(--color-border)', background: 'var(--color-bg-2)', display: 'flex', flexDirection: 'column' }}>
            <div className="mono text-xs font-bold" style={{ padding: '12px 16px', background: 'var(--border-subtle)', borderBottom: '1px solid var(--color-border)', color: 'var(--color-primary)' }}>
              /// FINANCIAL INTELLIGENCE
            </div>
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              {[
                { label: 'MRR', value: `$${mrr.toLocaleString()}`, color: 'var(--color-primary)' },
                { label: 'GROSS REVENUE', value: `$${totalRevenue.toLocaleString()}`, color: 'var(--color-success)' },
                { label: 'TOTAL EXPENSES', value: `-$${totalExpenses.toLocaleString()}`, color: 'var(--color-danger)' },
                { label: 'NET PROFIT', value: `$${netIncome.toLocaleString()}`, color: netIncome >= 0 ? 'var(--color-success)' : 'var(--color-danger)' },
              ].map(({ label, value, color }, idx) => (
                <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 16px', borderBottom: idx < 3 ? '1px solid var(--border-subtle)' : 'none', background: idx % 2 === 0 ? 'transparent' : '#000' }}>
                  <span className="mono text-xs" style={{ color: 'var(--color-text-2)' }}>{label}</span>
                  <span className="mono text-xs font-bold" style={{ color }}>{value}</span>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* ── EXPORTABLE BLOCK ── */}
        <div style={{ border: '1px solid var(--color-border)', background: 'var(--color-bg-2)', display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', background: 'var(--border-subtle)', borderBottom: '1px solid var(--color-border)' }}>
            <div className="mono text-xs font-bold" style={{ color: 'var(--color-primary)' }}>
              /// RAW TEXT DOSSIER
            </div>
            <button className="btn btn-ghost mono" style={{ fontSize: '9px', padding: '4px 12px', border: '1px solid var(--color-primary)', background: 'var(--color-primary)', color: '#000' }} onClick={copyReport}>
              {copied ? 'COPIED TO CLIPBOARD' : 'COPY RAW TXT'}
            </button>
          </div>
          <pre style={{ margin: 0, padding: '16px', fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--color-success)', background: '#000', whiteSpace: 'pre-wrap', lineHeight: '1.6' }}>
            {reportText}
          </pre>
        </div>

      </div>
    </div>
  )
}

export default Reports
